/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simoncherry_arcamera_codec_DataConvert */

#ifndef _Included_com_simoncherry_arcamera_codec_DataConvert
#define _Included_com_simoncherry_arcamera_codec_DataConvert
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_simoncherry_arcamera_codec_DataConvert
 * Method:    rgbaToYuv
 * Signature: ([BII[BI)V
 */
JNIEXPORT void JNICALL Java_com_simoncherry_arcamera_codec_DataConvert_rgbaToYuv
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
